version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            echo "$CIRCLE_BRANCH"
            echo "$CIRCLE_BUILD_NUM"
            echo "Tests go here, eventually"
      - run:
          name: Build the Sizzle CI Image
          command: |
            # TODO: make this only run when changes are present
            cd sizzle-terraform
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t stopthatastronaut/sizzle-ci:$TAG .
            if [[ "$CIRCLE_BRANCH" == "main" ]]
            then
              echo $DOCKER_PASSWORD | docker login -u stopthatastronaut --password-stdin
              docker push stopthatastronaut/sizzle-ci:$TAG
            fi
      - run:
          name: Build the sta-terraform image
          command: |
            # TODO: make this only run when changes are present
            cd sta-terraform
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t stopthatastronaut/sta-terraform:$TAG .
            if [[ "$CIRCLE_BRANCH" == "main" ]]
            then
              echo $DOCKER_PASSWORD | docker login -u stopthatastronaut --password-stdin
              docker push stopthatastronaut/sta-terraform:$TAG
            fi

workflows:
  build:
    jobs:
      - build:
          context:
            - DockerHub
