version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            echo "$CIRCLE_BRANCH"
            echo "$CIRCLE_BUILD_NUM"
            echo "Tests go here, eventually"
            docker --version
            docker image push --help
  build-sizzleci:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build the Sizzle CI Image
          command: |
            # TODO: make this only run when changes are present
            cd sizzle-terraform
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t stopthatastronaut/sizzle-ci:$TAG .
            docker tag stopthatastronaut/sizzle-ci:$TAG stopthatastronaut/sizzle-ci:latest
            if [[ "$CIRCLE_BRANCH" == "main" ]]
            then
              echo $DOCKER_PASSWORD | docker login -u stopthatastronaut --password-stdin
              docker image push stopthatastronaut/sizzle-ci:$TAG
              docker image push stopthatastronaut/sizzle-ci:latest
            fi
  build-staci:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build the sta-terraform image
          command: |
            # TODO: make this only run when changes are present
            cd sta-terraform
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t stopthatastronaut/sta-terraform:$TAG .
            docker tag stopthatastronaut/sta-terraform:$TAG stopthatastronaut/sta-terraform:latest
            if [[ "$CIRCLE_BRANCH" == "main" ]]
            then
              echo $DOCKER_PASSWORD | docker login -u stopthatastronaut --password-stdin
              docker image push stopthatastronaut/sta-terraform:$TAG
              docker image push stopthatastronaut/sta-terraform:latest
            fi
  build-openscad:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build the openscad image
          command: |
            # TODO: make this only run when changes are present
            # TODO: build without push on branches or PRs
            cd openscad
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t stopthatastronaut/openscad-tools:$TAG .
            docker tag stopthatastronaut/openscad-tools:$TAG stopthatastronaut/openscad-tools:latest
            if [[ "$CIRCLE_BRANCH" == "main" ]]
            then
              echo $DOCKER_PASSWORD | docker login -u stopthatastronaut --password-stdin
              docker image push stopthatastronaut/openscad-tools:$TAG
              docker image push stopthatastronaut/openscad-tools:latest
            fi

  build-octo:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build the octo image
          command: |
            # TODO: make this only run when changes are present
            # TODO: build without push on branches or PRs
            cd staocto
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t stopthatastronaut/sta-octo:$TAG .
            docker tag stopthatastronaut/sta-octo:$TAG stopthatastronaut/sta-octo:latest
            if [[ "$CIRCLE_BRANCH" == "main" ]]
            then
              echo $DOCKER_PASSWORD | docker login -u stopthatastronaut --password-stdin
              docker image push stopthatastronaut/sta-octo:$TAG
              docker image push stopthatastronaut/sta-octo:latest
            fi

workflows:
  build:
    jobs:
      - test:
          context:
            - DockerHub
      - build-sizzleci:
          context:
            - DockerHub
          requires:
            - test
      - build-staci:
          context:
            - DockerHub
          requires:
            - test
      - build-octo:
          context:
            - DockerHub
          requires:
            - test
